export const COLOR = {
  MAIN_WHITE: "#ffffff",
  MAIN_BLACK: "#050E04",
  MAIN_GREEN: "#8EDF82",
  MAIN_GREEN_HOVER: "#AAE7A1",
  MAIN_DARK_GREEN: "#5CAF50",
  MAIN_LIME: "#DCFA5C",
  MAIN_ORANGE: "#F29E48",
  LIGHT_GRAY: "#E7E7E7", // 버튼 비활성화 배경 색
  MEDIUM_GRAY: "#d9d9d9",
  DARK_GRAY: "#7A7D81", // 버튼 비활성화 글씨 색
  INPUT_GRAY: "#F3F3F3",
  INPUT_BORDER_GRAY: "#BEC2C6",
  FOOTER_GRAY: "#f2f2f2",
};
