version: '3'
services:
  mysql:
    image: mysql:8
    container_name: plogging_application_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plogging
